version: '3.8'

services:
  # MariaDB Database Service
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hrdb
      MYSQL_USER: hruser
      MYSQL_PASSWORD: hrpassword
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - hr-network
    ports:
      - "3306:3306"
networks:
  hr-network:
    driver: bridge

volumes:
  mariadb_data:
